---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
    config: 
      file: '.rubocop.yml'
    channel: rubocop-0-48
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
exclude_paths:
- config/
- db/
- node_modules/
- spec/
- vendor/
